"""initial migration

Revision ID: 21d841f7aac8
Revises: 
Create Date: 2026-01-21 01:22:16.040399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa 
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '21d841f7aac8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('groups',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contribution_amount', sa.Float(), nullable=False),
    sa.Column('contribution_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invite_code', sa.String(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_groups_invite_code'), 'groups', ['invite_code'], unique=True)
    op.create_table('wallets',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('locked_balance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('group_members',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('group_uid', sa.Uuid(), nullable=True),
    sa.Column('user_uid', sa.Uuid(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_uid'], ['groups.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('group_wallets',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('group_uid', sa.Uuid(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_uid'], ['groups.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('messages',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('group_uid', sa.Uuid(), nullable=True),
    sa.Column('sender_uid', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_uid'], ['groups.uid'], ),
    sa.ForeignKeyConstraint(['sender_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_messages_sender_uid'), 'messages', ['sender_uid'], unique=False)
    op.create_table('transactions',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'TRANSFER', 'CONTRIBUTION', 'DISBURSEMENT', name='transactiontype'), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='transactionstatus'), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('from_user_uid', sa.Uuid(), nullable=True),
    sa.Column('to_user_uid', sa.Uuid(), nullable=True),
    sa.Column('group_uid', sa.Uuid(), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mobile_money_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['group_uid'], ['groups.uid'], ),
    sa.ForeignKeyConstraint(['to_user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_transactions_external_reference'), 'transactions', ['external_reference'], unique=True)
    op.create_index(op.f('ix_transactions_from_user_uid'), 'transactions', ['from_user_uid'], unique=False)
    op.create_index(op.f('ix_transactions_group_uid'), 'transactions', ['group_uid'], unique=False)
    op.create_index(op.f('ix_transactions_to_user_uid'), 'transactions', ['to_user_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_to_user_uid'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_group_uid'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_from_user_uid'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_reference'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_messages_sender_uid'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('group_wallets')
    op.drop_table('group_members')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_groups_invite_code'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
