"""initial migration3

Revision ID: 4a8f255ba28c
Revises: 69da9a840a29
Create Date: 2026-01-21 06:21:43.511035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa 
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4a8f255ba28c'
down_revision: Union[str, None] = '69da9a840a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('policies', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'policies')
    # ### end Alembic commands ###
